"""Hazard function models for time-to-event generation.

Replaces C# Hazard.cs (GompHazard, ExpHazard, LogLogisticHazard, Piecewise).
All hazard classes expose:
    - get_value(time, covariate=0) -> hazard rate h(t)
    - get_log(time, covariate=0) -> log hazard
    - H0(start, end) -> cumulative baseline hazard
    - iH0(value) -> inverse cumulative baseline hazard
    - T(start, covariate=0) -> random time sampled via inverse method
    - update() -> refresh internal state (for objects with mutable params)

Key mathematical principle: for a proportional hazards model
    h(t | z) = h0(t) * exp(z * beta),
the cumulative hazard is
    H(t | z) = H0(t) * exp(z * beta),
and the survival function is S(t) = exp(-H(t)).

Random event time T is generated by solving:
    U ~ Uniform(0,1)
    H0(T) - H0(start) = -log(U) / exp(covariate)
    T = iH0( H0(start) - log(U)/exp(covariate) )
"""

from abc import ABC, abstractmethod
from typing import Optional
import numpy as np


class Hazard(ABC):
    """Abstract base class for hazard functions."""
    
    def __init__(self, constants: np.ndarray):
        self.constants = np.asarray(constants, dtype=np.float64)
    
    @abstractmethod
    def get_value(self, time: float, covariate: float = 0.0) -> float:
        """Evaluate hazard rate h(time | covariate). Vectorized-ready."""
        ...
    
    @abstractmethod
    def get_log(self, time: float, covariate: float = 0.0) -> float:
        """Evaluate log hazard."""
        ...
    
    @abstractmethod
    def H0(self, start: float, end: float) -> float:
        """Cumulative baseline hazard from start to end."""
        ...
    
    @abstractmethod
    def iH0(self, value: float) -> float:
        """Inverse cumulative baseline hazard."""
        ...
    
    def T(self, start: float, covariate: float = 0.0) -> float:
        """Generate random time from the hazard distribution.
        
        Uses the inverse CDF method: sample U ~ Uniform(0,1),
        then solve H0(T) = H0(start) - log(U)/exp(covariate).
        
        Equivalent to C# Hazard.T(start, covariates).
        
        Parameters
        ----------
        start : float
            Left truncation time (current age).
        covariate : float
            Linear predictor z*beta for proportional hazards adjustment.
        
        Returns
        -------
        float
            Sampled event time. Returns unreal_life_length if no event.
        """
        from .random import get_random
        rng = get_random()
        
        ecov = np.exp(covariate)
        tH = self.H0(0.0, start)
        u = rng.next_double()
        r = -np.log(u)
        val = tH + r / ecov
        
        T_val = self.iH0(val)
        
        if np.isinf(T_val) or np.isnan(T_val):
            return float(np.iinfo(np.int16).max)  # 32767 — unreachable age
        return abs(T_val)
    
    def T_batch(self, start: np.ndarray, covariate: np.ndarray) -> np.ndarray:
        """Vectorized batch version of T() for multiple agents.
        
        Parameters
        ----------
        start : np.ndarray
            Left truncation times for each agent.
        covariate : np.ndarray
            Linear predictors for each agent.
        
        Returns
        -------
        np.ndarray
            Sampled event times.
        """
        from .random import get_random
        rng = get_random()
        
        n = len(start)
        ecov = np.exp(covariate)
        u = rng.next_doubles(n)
        r = -np.log(np.maximum(u, 1e-300))
        
        # Compute tH = H0(0, start) for each agent
        # For subclasses with analytical H0, this must be overridden for vectorization
        tH = np.array([self.H0(0.0, float(s)) for s in start])
        val = tH + r / ecov
        
        # iH0 must also support vectorized input
        T_vals = np.array([self.iH0(float(v)) for v in val])
        T_vals = np.where(np.isfinite(T_vals), np.abs(T_vals), float(np.iinfo(np.int16).max))
        return T_vals
    
    def update(self):
        """Update internal state after parameter change. Override in subclasses."""
        pass


class GompHazard(Hazard):
    """Gompertz hazard: h(t) = exp(-L + B*t + covariate).
    
    Gompertz distribution is standard for modeling human mortality.
    
    Parameters
    ----------
    lambda_ : float
        Intercept parameter L. Higher L -> lower baseline hazard.
    beta : float
        Age slope parameter B. Higher B -> faster hazard increase with age.
    """
    
    def __init__(self, lambda_: float, beta: float):
        super().__init__(np.array([lambda_, beta]))
        self.L = lambda_
        self.B = beta
    
    @property
    def L_val(self) -> float:
        return self.constants[0]
    
    @property
    def B_val(self) -> float:
        return self.constants[1]
    
    def get_value(self, time: float, covariate: float = 0.0) -> float:
        return np.exp(-self.L_val + self.B_val * time + covariate)
    
    def get_log(self, time: float, covariate: float = 0.0) -> float:
        return -self.L_val + self.B_val * time + covariate
    
    def H0(self, start: float, end: float) -> float:
        H0 = np.exp(-self.L_val) / self.B_val
        H = H0 * (np.exp(self.B_val * start) - np.exp(self.B_val * end))
        return H
    
    def iH0(self, value: float) -> float:
        log_iH = (self.B_val * value / np.exp(-self.L_val)) + 1.0
        if log_iH <= 0:
            return float(np.iinfo(np.int16).max)
        iH = np.log(log_iH) / self.B_val
        return iH


class ExpHazard(Hazard):
    """Exponential (constant) hazard: h(t) = exp(L + covariate).
    
    Memoryless distribution. L = log(lambda).
    Used in the original C# model for cancer death hazard.
    
    Parameters
    ----------
    constant : float
        L parameter. lambda = exp(L).
    """
    
    def __init__(self, constant: float):
        super().__init__(np.array([constant]))
        self.L = constant
    
    @property
    def L_val(self) -> float:
        return self.constants[0]
    
    def get_value(self, time: float, covariate: float = 0.0) -> float:
        return np.exp(self.L_val + covariate)
    
    def get_log(self, time: float, covariate: float = 0.0) -> float:
        return self.L_val + covariate
    
    def H0(self, start: float, end: float) -> float:
        return np.exp(self.L_val) * (end - start)
    
    def iH0(self, value: float) -> float:
        return value / np.exp(self.L_val)


class LogLogisticHazard(Hazard):
    """Log-logistic hazard: h(t) = exp(-O) * k * t^{k-1} / (1 + exp(-O) * t^k).
    
    Parameters
    ----------
    O : float
        Log-odds intercept. Higher O -> lower hazard.
    k : float
        Shape parameter. k > 1: increasing then decreasing hazard (unimodal).
        k < 1: decreasing hazard. k = 1: reduces to a simpler form.
    """
    
    def __init__(self, O: float, k: float):
        super().__init__(np.array([O, k]))
        self.O = O
        self.k = k
    
    @property
    def O_val(self) -> float:
        return self.constants[0]
    
    @property
    def k_val(self) -> float:
        return self.constants[1]
    
    def get_value(self, time: float, covariate: float = 0.0) -> float:
        ecov = np.exp(covariate)
        t_adj = time * ecov
        num = np.exp(-self.O_val) * self.k_val * t_adj ** (self.k_val - 1)
        denom = 1.0 + np.exp(-self.O_val) * t_adj ** self.k_val
        return num / denom
    
    def get_log(self, time: float, covariate: float = 0.0) -> float:
        return np.log(self.get_value(time, covariate))
    
    def H0(self, start: float, end: float) -> float:
        S = 1.0 / (1.0 + np.exp(-self.O_val) * end ** self.k_val)
        return -np.log(S)
    
    def iH0(self, value: float) -> float:
        under = (np.exp(value) - 1.0) / np.exp(-self.O_val)
        return under ** (1.0 / self.k_val)


class PiecewiseHazard(Hazard):
    """Piecewise constant log-hazard with Heaviside step changes.
    
    log h(t) = beta_0 + sum_{k=1}^{K} beta_k * H(t - t_k)
    
    where H(x) = 1 if x >= 0 else 0 (Heaviside step function).
    
    This is the primary hazard model for diagnosis in the original C# code.
    Values are pre-computed and cached for ages 0..119 for performance.
    
    Parameters
    ----------
    constants : np.ndarray
        Array [beta_0, beta_1, ..., beta_K] of log-hazard coefficients.
    years : np.ndarray
        Array [t_1, ..., t_K] of age thresholds corresponding to beta_1..beta_K.
    unreal_life_length : int
        Maximum age to pre-compute.
    """
    
    def __init__(self, constants: np.ndarray, years: np.ndarray, unreal_life_length: int = 110):
        super().__init__(constants)
        self.years = np.asarray(years, dtype=np.float64)
        self.unreal_life_length = unreal_life_length
        self.value_by_age: np.ndarray = np.zeros(unreal_life_length + 1, dtype=np.float64)
        self._build_cache()
    
    @property
    def beta0(self) -> float:
        return self.constants[0]
    
    def _calc_for_year(self, year: float) -> float:
        """Compute log-hazard and exponentiate, clamping to [0, 1]."""
        result = self.constants[0]  # beta_0
        for i in range(1, len(self.constants)):
            result += self.constants[i] * (1.0 if year >= self.years[i - 1] else 0.0)
        val = np.exp(result)
        return min(val, 1.0)
    
    def _build_cache(self):
        """Pre-compute hazard values for all ages."""
        for i in range(self.unreal_life_length + 1):
            self.value_by_age[i] = self._calc_for_year(float(i))
    
    def get_value(self, time: float, covariate: float = 0.0) -> float:
        t_int = int(time)
        if t_int >= len(self.value_by_age):
            return self.value_by_age[-1]
        return self.value_by_age[t_int]
    
    def get_log(self, time: float, covariate: float = 0.0) -> float:
        val = self.get_value(time, covariate)
        if val <= 0:
            return -np.inf
        return np.log(val)
    
    def H0(self, start: float, end: float) -> float:
        # Not analytically defined for piecewise discrete — return 0
        return 0.0
    
    def iH0(self, value: float) -> float:
        # Not analytically defined — return 0
        return 0.0
    
    def T(self, start: float, covariate: float = 0.0) -> float:
        """Generate event time by discrete Bernoulli trials at each age.
        
        Equivalent to the C# Piecewise.T() method: for each age i from 0 to
        unreal_life_length, check if Ber(h(i)) == 1. The first success age
        is the event time. If no success, return unreal_life_length.
        """
        from .random import get_random
        rng = get_random()
        
        max_age = min(self.unreal_life_length, len(self.value_by_age))
        
        # Generate all Bernoulli trials in one batch (vectorized)
        uniforms = rng.next_doubles(max_age)
        hazards = self.value_by_age[:max_age]
        
        # Find first index where uniform < hazard
        successes = uniforms < hazards
        idx = np.argmax(successes)  # argmax returns first True index
        if successes[idx]:
            return float(idx)
        
        return float(self.unreal_life_length)
    
    def T_batch(self, start: np.ndarray, covariate: np.ndarray) -> np.ndarray:
        """Vectorized batch: generate event times for multiple agents."""
        from .random import get_random
        rng = get_random()
        
        n = len(start)
        max_age = min(self.unreal_life_length, len(self.value_by_age))
        
        # Generate all uniforms in one batch: shape (n, max_age)
        uniforms = rng.rng.uniform(0.0, 1.0, size=(n, max_age))
        hazards = self.value_by_age[:max_age].reshape(1, -1)  # broadcastable
        
        successes = uniforms < hazards
        # argmax along axis=1 gives first True column for each row
        indices = np.argmax(successes, axis=1)
        has_success = successes[np.arange(n), indices]
        
        result = np.where(has_success, indices.astype(np.float64), float(self.unreal_life_length))
        return result
    
    def update(self):
        """Rebuild the hazard cache after parameter changes."""
        self._build_cache()


def parse_hazard(spec: str, unreal_life_length: int = 110) -> Hazard:
    """Parse a hazard specification string into a Hazard object.
    
    Formats (compatible with C# Parameters.ParseHazard):
        "gomp, L, B"              -> GompHazard(L, B)
        "exp, L"                  -> ExpHazard(L)
        "loglog, O, k"            -> LogLogisticHazard(O, k)
        "piecewise, t1@c1;t2@c2"  -> PiecewiseHazard([c1,c2,...], [t1,t2,...])
    
    Parameters
    ----------
    spec : str
        Hazard specification string (same format as C# parameters.txt).
    unreal_life_length : int
        Maximum age for piecewise hazard cache.
    
    Returns
    -------
    Hazard
        Instantiated hazard object.
    """
    parts = [p.strip() for p in spec.split(',')]
    htype = parts[0].lower()
    
    if htype == 'gomp':
        L = float(parts[1])
        B = float(parts[2])
        return GompHazard(L, B)
    elif htype == 'loglog':
        O = float(parts[1])
        k = float(parts[2])
        return LogLogisticHazard(O, k)
    elif htype == 'piecewise':
        # Format: "piecewise, t1@c1;t2@c2;..."
        pairs = parts[1].split(';')
        years = []
        coefs = []
        for pair in pairs:
            pair = pair.strip()
            if '@' in pair:
                y, c = pair.split('@')
                years.append(float(y.strip()))
                coefs.append(float(c.strip()))
        # First coefficient is the base (at age -1 in C#)
        # Rest are step changes at given ages
        return PiecewiseHazard(np.array(coefs), np.array(years), unreal_life_length)
    else:
        # Default: exponential
        L = float(parts[1])
        return ExpHazard(L)